"""ArbiterOS governance layer for trading.

This module provides the ArbiterOS instance and decorator utilities for wrapping
agent node functions with policy-driven governance.

Generated by ArbiterOS Migration Tool.
"""

import functools
import logging
from typing import Any, Callable, TypeVar

from arbiteros_alpha import ArbiterOSAlpha
from arbiteros_alpha.instructions import (
    CognitiveCore,
    ExecutionCore,
    MemoryCore,
    NormativeCore,
    SocialCore,
)

logger = logging.getLogger(__name__)

# Global ArbiterOS instance for the trading framework
arbiter_os = ArbiterOSAlpha(backend="langgraph")

# Instruction type mappings for different agent roles
TICKER_INSTRUCTION = ExecutionCore.TOOL_CALL
DECORATOR_INSTRUCTION = MemoryCore.STRUCTURE
BULL_RESEARCHER_INSTRUCTION = CognitiveCore.GENERATE
BEAR_RESEARCHER_INSTRUCTION = CognitiveCore.GENERATE
SAFE_DEBATOR_INSTRUCTION = SocialCore.NEGOTIATE
NEUTRAL_DEBATOR_INSTRUCTION = SocialCore.NEGOTIATE
RISKY_DEBATOR_INSTRUCTION = SocialCore.NEGOTIATE
TRADER_INSTRUCTION = ExecutionCore.TOOL_CALL
RISK_MANAGER_INSTRUCTION = NormativeCore.VERIFY
RESEARCH_MANAGER_INSTRUCTION = ExecutionCore.DELEGATE
MSG_DELETE_INSTRUCTION = MemoryCore.FILTER
MARKET_ANALYST_INSTRUCTION = CognitiveCore.GENERATE
SOCIAL_MEDIA_ANALYST_INSTRUCTION = CognitiveCore.GENERATE
NEWS_ANALYST_INSTRUCTION = CognitiveCore.GENERATE
FUNDAMENTALS_ANALYST_INSTRUCTION = CognitiveCore.GENERATE

# Type variable for function decoration
F = TypeVar("F", bound=Callable[..., Any])


def govern_ticker(func: F) -> F:
    """Decorator wrapper for ticker functions.

    Applies TOOL_CALL instruction type governance to functions
    that The function 'init_ticker' is a decorator that initializes an external tool (yf.Ticker) and passes it to the function. This aligns with the TOOL_CALL instruction type, which involves executing predefined external functions..

    Args:
        func: The node function to wrap.

    Returns:
        The wrapped function with ArbiterOS governance.
    """
    return arbiter_os.instruction(TICKER_INSTRUCTION)(func)


def govern_decorator(func: F) -> F:
    """Decorator wrapper for decorator functions.

    Applies STRUCTURE instruction type governance to functions
    that The function 'decorate_all_methods' applies a decorator to all methods of a class, effectively structuring the class's behavior. This aligns with the STRUCTURE instruction type, which involves transforming unstructured text into a structured format..

    Args:
        func: The node function to wrap.

    Returns:
        The wrapped function with ArbiterOS governance.
    """
    return arbiter_os.instruction(DECORATOR_INSTRUCTION)(func)


def govern_bull_researcher(func: F) -> F:
    """Decorator wrapper for bull_researcher functions.

    Applies GENERATE instruction type governance to functions
    that The 'create_bull_researcher' function generates a bull research node that analyzes market data to identify bullish trends and opportunities. This aligns with the GENERATE instruction type, which involves content generation and reasoning..

    Args:
        func: The node function to wrap.

    Returns:
        The wrapped function with ArbiterOS governance.
    """
    return arbiter_os.instruction(BULL_RESEARCHER_INSTRUCTION)(func)


def govern_bear_researcher(func: F) -> F:
    """Decorator wrapper for bear_researcher functions.

    Applies GENERATE instruction type governance to functions
    that The 'create_bear_researcher' function generates a bear research node that analyzes market data to identify bearish trends and risks. This aligns with the GENERATE instruction type, which involves content generation and reasoning..

    Args:
        func: The node function to wrap.

    Returns:
        The wrapped function with ArbiterOS governance.
    """
    return arbiter_os.instruction(BEAR_RESEARCHER_INSTRUCTION)(func)


def govern_safe_debator(func: F) -> F:
    """Decorator wrapper for safe_debator functions.

    Applies NEGOTIATE instruction type governance to functions
    that The 'create_safe_debator' function generates a node that engages in risk management discussions with a conservative approach, which involves negotiation and dialogue. This aligns with the NEGOTIATE instruction type..

    Args:
        func: The node function to wrap.

    Returns:
        The wrapped function with ArbiterOS governance.
    """
    return arbiter_os.instruction(SAFE_DEBATOR_INSTRUCTION)(func)


def govern_neutral_debator(func: F) -> F:
    """Decorator wrapper for neutral_debator functions.

    Applies NEGOTIATE instruction type governance to functions
    that The 'create_neutral_debator' function generates a node that engages in risk management discussions with a neutral approach, which involves negotiation and dialogue. This aligns with the NEGOTIATE instruction type..

    Args:
        func: The node function to wrap.

    Returns:
        The wrapped function with ArbiterOS governance.
    """
    return arbiter_os.instruction(NEUTRAL_DEBATOR_INSTRUCTION)(func)


def govern_risky_debator(func: F) -> F:
    """Decorator wrapper for risky_debator functions.

    Applies NEGOTIATE instruction type governance to functions
    that The 'create_risky_debator' function generates a node that engages in risk management discussions with an aggressive approach, which involves negotiation and dialogue. This aligns with the NEGOTIATE instruction type..

    Args:
        func: The node function to wrap.

    Returns:
        The wrapped function with ArbiterOS governance.
    """
    return arbiter_os.instruction(RISKY_DEBATOR_INSTRUCTION)(func)


def govern_trader(func: F) -> F:
    """Decorator wrapper for trader functions.

    Applies TOOL_CALL instruction type governance to functions
    that The 'create_trader' function generates a trader node that executes trades based on analysis and recommendations, which involves interacting with external systems or APIs. This aligns with the TOOL_CALL instruction type..

    Args:
        func: The node function to wrap.

    Returns:
        The wrapped function with ArbiterOS governance.
    """
    return arbiter_os.instruction(TRADER_INSTRUCTION)(func)


def govern_risk_manager(func: F) -> F:
    """Decorator wrapper for risk_manager functions.

    Applies VERIFY instruction type governance to functions
    that The 'create_risk_manager' function generates a node that assesses and manages risks associated with trading decisions, ensuring correctness and compliance. This aligns with the VERIFY instruction type..

    Args:
        func: The node function to wrap.

    Returns:
        The wrapped function with ArbiterOS governance.
    """
    return arbiter_os.instruction(RISK_MANAGER_INSTRUCTION)(func)


def govern_research_manager(func: F) -> F:
    """Decorator wrapper for research_manager functions.

    Applies DELEGATE instruction type governance to functions
    that The 'create_research_manager' function generates a node that oversees the research process, coordinating between bull and bear researchers. This involves delegating tasks, aligning with the DELEGATE instruction type..

    Args:
        func: The node function to wrap.

    Returns:
        The wrapped function with ArbiterOS governance.
    """
    return arbiter_os.instruction(RESEARCH_MANAGER_INSTRUCTION)(func)


def govern_msg_delete(func: F) -> F:
    """Decorator wrapper for msg_delete functions.

    Applies FILTER instruction type governance to functions
    that The 'create_msg_delete' function generates a node that clears messages, effectively filtering out unnecessary information. This aligns with the FILTER instruction type, which involves pruning context to keep only relevant information..

    Args:
        func: The node function to wrap.

    Returns:
        The wrapped function with ArbiterOS governance.
    """
    return arbiter_os.instruction(MSG_DELETE_INSTRUCTION)(func)


def govern_market_analyst(func: F) -> F:
    """Decorator wrapper for market_analyst functions.

    Applies GENERATE instruction type governance to functions
    that The 'create_market_analyst' function generates a market analyst node that analyzes financial markets and selects relevant indicators, which involves content generation and reasoning. This aligns with the GENERATE instruction type..

    Args:
        func: The node function to wrap.

    Returns:
        The wrapped function with ArbiterOS governance.
    """
    return arbiter_os.instruction(MARKET_ANALYST_INSTRUCTION)(func)


def govern_social_media_analyst(func: F) -> F:
    """Decorator wrapper for social_media_analyst functions.

    Applies GENERATE instruction type governance to functions
    that The 'create_social_media_analyst' function generates a social media analyst node that analyzes social media posts and sentiment, which involves content generation and reasoning. This aligns with the GENERATE instruction type..

    Args:
        func: The node function to wrap.

    Returns:
        The wrapped function with ArbiterOS governance.
    """
    return arbiter_os.instruction(SOCIAL_MEDIA_ANALYST_INSTRUCTION)(func)


def govern_news_analyst(func: F) -> F:
    """Decorator wrapper for news_analyst functions.

    Applies GENERATE instruction type governance to functions
    that The 'create_news_analyst' function generates a news analyst node that analyzes recent news and trends, which involves content generation and reasoning. This aligns with the GENERATE instruction type..

    Args:
        func: The node function to wrap.

    Returns:
        The wrapped function with ArbiterOS governance.
    """
    return arbiter_os.instruction(NEWS_ANALYST_INSTRUCTION)(func)


def govern_fundamentals_analyst(func: F) -> F:
    """Decorator wrapper for fundamentals_analyst functions.

    Applies GENERATE instruction type governance to functions
    that The 'create_fundamentals_analyst' function generates a fundamentals analyst node that analyzes fundamental information about a company, which involves content generation and reasoning. This aligns with the GENERATE instruction type..

    Args:
        func: The node function to wrap.

    Returns:
        The wrapped function with ArbiterOS governance.
    """
    return arbiter_os.instruction(FUNDAMENTALS_ANALYST_INSTRUCTION)(func)


def wrap_factory_result(wrapper_func: Callable[[F], F]) -> Callable:
    """Higher-order decorator for wrapping factory function results.

    This decorator is used to wrap the inner function returned by agent
    factory functions without modifying the factory function itself.

    Args:
        wrapper_func: The governance wrapper to apply.

    Returns:
        A decorator that wraps the result of the factory function.

    Example:
        >>> @wrap_factory_result(govern_analyst)
        ... def create_analyst(llm):
        ...     def analyst_node(state):
        ...         return {"report": "..."}
        ...     return analyst_node
    """

    def factory_decorator(factory_func: Callable) -> Callable:
        @functools.wraps(factory_func)
        def wrapper(*args, **kwargs):
            # Call the original factory to get the node function
            node_func = factory_func(*args, **kwargs)
            # Wrap the node function with governance
            governed_func = wrapper_func(node_func)
            return governed_func

        return wrapper

    return factory_decorator


def get_arbiter_os() -> ArbiterOSAlpha:
    """Get the global ArbiterOS instance.

    Returns:
        The configured ArbiterOSAlpha instance.
    """
    return arbiter_os


def reset_arbiter_os() -> None:
    """Reset the global ArbiterOS instance.

    Creates a new ArbiterOS instance, clearing all history and policies.
    Useful for testing or when starting fresh executions.
    """
    global arbiter_os
    arbiter_os = ArbiterOSAlpha(backend="langgraph")
    logger.info("ArbiterOS instance reset")